import Sidebar from '@/components/sidebar';
import type { Metadata } from 'next';
import { Suspense } from 'react';
import './globals.css';
import Providers from './providers';

export const metadata: Metadata = {
  title: 'VP TODO',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="min-h-dvh bg-background text-foreground">
            <div className="flex">
              <aside className="hidden md:block w-72 border-r border-border/60">
                <Suspense
                  fallback={
                    <div className="p-4 text-sm text-muted-foreground">
                      Loading...
                    </div>
                  }
                >
                  <Sidebar />
                </Suspense>
              </aside>

              <main className="flex-1">
                <div className="mx-auto max-w-6xl p-6">{children}</div>
              </main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
